server:
  port: 0 # 0: random port -> 단일 컨테이너 환경이라면 추천 
          # ${random.int(50000,51000)} -> port 범위지정 안쓰는게 좋다. 
  
spring:
  application:
    name: user-service

eureka:
  instance: #instance-id를 지정해줌으로써, random시 0번 하나만 보이는 경우 막음
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    #instance-id:  ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true #eureka client로 등록
    fetch-registry: true #Eureka 서버로부터 인스턴스들의 정보를 주기적으로 가져옴, 갱신된 정보를 받겠다는 설정
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # eureka url 지정
      
                            
   